# Generated by Django 2.2.2 on 2019-06-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(),
        ),
    ]
